/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'expectedPaymentDate' : string,
  'holdFlag' : boolean,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'amountText' : string,
  'updatedAt' : bigint,
  'address' : string,
  'contactNo' : string,
  'allClearFlag' : boolean,
  'consumerNo' : string,
  'product' : string,
}
export interface _SERVICE {
  'createOrder' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'deleteOrder' : ActorMethod<[bigint], boolean>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'listOrders' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'orders' : Array<Order> }
  >,
  'searchOrders' : ActorMethod<[string], Array<Order>>,
  'updateOrder' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];