/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'expectedPaymentDate' : IDL.Text,
  'holdFlag' : IDL.Bool,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'amountText' : IDL.Text,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
  'contactNo' : IDL.Text,
  'allClearFlag' : IDL.Bool,
  'consumerNo' : IDL.Text,
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'listOrders' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'orders' : IDL.Vec(Order) })],
      ['query'],
    ),
  'searchOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'updateOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'expectedPaymentDate' : IDL.Text,
    'holdFlag' : IDL.Bool,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'amountText' : IDL.Text,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
    'contactNo' : IDL.Text,
    'allClearFlag' : IDL.Bool,
    'consumerNo' : IDL.Text,
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'listOrders' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'orders' : IDL.Vec(Order) })],
        ['query'],
      ),
    'searchOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'updateOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };