/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppUser = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : IDL.Int,
  'roles' : IDL.Vec(IDL.Nat),
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'performedBy' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'collectDate' : IDL.Text,
  'orderDate' : IDL.Text,
  'isHeld' : IDL.Bool,
  'orderId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'paymentDate' : IDL.Text,
  'quantity' : IDL.Nat,
  'contactNo' : IDL.Text,
  'isAllClear' : IDL.Bool,
  'expectedDelivery' : IDL.Text,
  'amount' : IDL.Float64,
  'consumerNo' : IDL.Text,
  'product' : IDL.Text,
});
export const AppRole = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Stage = IDL.Record({
  'id' : IDL.Nat,
  'assignedRoles' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'sfaEnabled' : IDL.Bool,
  'orderIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  'appendAudit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignRoles' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'createRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createStage' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
      [],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Nat], [], []),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(AppUser)], ['query']),
  'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'listAuditLog' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'listOrders' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'orders' : IDL.Vec(Order) })],
      ['query'],
    ),
  'listRoles' : IDL.Func([], [IDL.Vec(AppRole)], ['query']),
  'listStages' : IDL.Func([], [IDL.Vec(Stage)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'loginWithPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AppUser)], []),
  'registerSelf' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'registerWithPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'setAllClearFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setHoldFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'customerName' : IDL.Text,
          'status' : IDL.Text,
          'paymentStatus' : IDL.Text,
          'collectDate' : IDL.Text,
          'orderDate' : IDL.Text,
          'orderId' : IDL.Text,
          'address' : IDL.Text,
          'notes' : IDL.Text,
          'paymentDate' : IDL.Text,
          'quantity' : IDL.Nat,
          'contactNo' : IDL.Text,
          'expectedDelivery' : IDL.Text,
          'amount' : IDL.Float64,
          'consumerNo' : IDL.Text,
          'product' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'updateStage' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'assignedRoles' : IDL.Vec(IDL.Nat),
          'name' : IDL.Text,
          'sfaEnabled' : IDL.Bool,
          'orderIndex' : IDL.Nat,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppUser = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : IDL.Int,
    'roles' : IDL.Vec(IDL.Nat),
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'performedBy' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'collectDate' : IDL.Text,
    'orderDate' : IDL.Text,
    'isHeld' : IDL.Bool,
    'orderId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'paymentDate' : IDL.Text,
    'quantity' : IDL.Nat,
    'contactNo' : IDL.Text,
    'isAllClear' : IDL.Bool,
    'expectedDelivery' : IDL.Text,
    'amount' : IDL.Float64,
    'consumerNo' : IDL.Text,
    'product' : IDL.Text,
  });
  const AppRole = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Stage = IDL.Record({
    'id' : IDL.Nat,
    'assignedRoles' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'sfaEnabled' : IDL.Bool,
    'orderIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    'appendAudit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignRoles' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'createRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createStage' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
        [],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Nat], [], []),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(AppUser)], ['query']),
    'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'listAuditLog' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'listOrders' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'orders' : IDL.Vec(Order) })],
        ['query'],
      ),
    'listRoles' : IDL.Func([], [IDL.Vec(AppRole)], ['query']),
    'listStages' : IDL.Func([], [IDL.Vec(Stage)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'loginWithPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(AppUser)],
        [],
      ),
    'registerSelf' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'registerWithPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'setAllClearFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setHoldFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'customerName' : IDL.Text,
            'status' : IDL.Text,
            'paymentStatus' : IDL.Text,
            'collectDate' : IDL.Text,
            'orderDate' : IDL.Text,
            'orderId' : IDL.Text,
            'address' : IDL.Text,
            'notes' : IDL.Text,
            'paymentDate' : IDL.Text,
            'quantity' : IDL.Nat,
            'contactNo' : IDL.Text,
            'expectedDelivery' : IDL.Text,
            'amount' : IDL.Float64,
            'consumerNo' : IDL.Text,
            'product' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'updateStage' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'assignedRoles' : IDL.Vec(IDL.Nat),
            'name' : IDL.Text,
            'sfaEnabled' : IDL.Bool,
            'orderIndex' : IDL.Nat,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };